ci:
  autoupdate_commit_msg: "MAINT: autoupdate pre-commit config"
  autoupdate_schedule: quarterly

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/ComPWA/policy
    rev: 0.3.18
    hooks:
      - id: fix-nbformat-version
      - id: remove-empty-tags

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker
        name: editorconfig
        alias: ec
        exclude: >-
          (?x)^(
            .*\.py
          )$

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args:
          - --extra-keys
          - |
            cell.attachments
            cell.metadata.editable
            cell.metadata.id
            cell.metadata.slideshow

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: >-
          (?x)^(
            .*\.ipynb
          )$

  - repo: https://github.com/redeboer/taplo-pre-commit
    rev: 0.9.1rc1
    hooks:
      - id: taplo

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args:
          - --in-place

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
