ci:
  autoupdate_commit_msg: "MAINT: update lock files"
  autoupdate_schedule: quarterly
  skip:
    - uv-lock

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/ComPWA/policy
    rev: 0.5.18
    hooks:
      - id: check-dev-files
        args:
          - --doc-apt-packages=graphviz
          - --github-pages
          - --no-cd
          - --no-pypi
          - --repo-name=gluex-nstar
          - --repo-name="Symbolic Amplitudes for Light Baryons"
      - id: fix-nbformat-version
      - id: remove-empty-tags

      - id: set-nb-display-name
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        args:
          - --drop-empty-cells
          - --extra-keys
          - |
            cell.attachments
            cell.metadata.code_folding
            cell.metadata.editable
            cell.metadata.id
            cell.metadata.pycharm
            cell.metadata.slideshow
            cell.metadata.user_expressions
            metadata.celltoolbar
            metadata.colab.name
            metadata.colab.provenance
            metadata.interpreter
            metadata.notify_time
            metadata.toc
            metadata.toc-autonumbering
            metadata.toc-showcode
            metadata.toc-showmarkdowntxt
            metadata.toc-showtags
            metadata.varInspector
            metadata.vscode

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/ComPWA/prettier-pre-commit
    rev: v3.4.2
    hooks:
      - id: prettier
        exclude: >-
          (?x)^(
            .*\.ipynb
          )$

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort
        args:
          - --in-place

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.1.2
    hooks:
      - id: editorconfig-checker
        name: editorconfig
        alias: ec
        exclude: >-
          (?x)^(
            .*\.py
          )$

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.24
    hooks:
      - id: uv-lock
