version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_install:
      - curl -fsSL https://pixi.sh/install.sh | bash
      - |-
        /home/.pixi/bin/pixi pixi shell

sphinx:
  builder: html
  configuration: docs/conf.py
