version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

commands:
  - curl -sSL https://install.pixi.dev | sh
  - pixi install
  - pixi run docnb
