version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  steps:
    - run:
        cmd: curl -sSL https://install.pixi.dev | sh
    - run:
        cmd: pixi install
    - run:
        cmd: pixi run docnb
sphinx:
  configuration: docs/conf.py
