version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_install:
      - curl -fsSL https://pixi.sh/install.sh | bash
    pre_build:
      - export PATH="$HOME/.pixi/bin:$PATH" && pixi shell

python:
  install:
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
