[project]
authors = ["Vitor Shen <17490173+shenvitor@users.noreply.github.com>"]
channels = ["conda-forge"]
license = "MIT"
license-file = "LICENSE"
name = "gluex-nstar"
platforms = ["linux-64"]
readme = "README.md"

[tasks.doc]
cmd = """
sphinx-build \
    -nW --keep-going \
    -b html \
    docs/ docs/_build/html
"""

[tasks.doclive]
cmd = """
sphinx-autobuild \
    --watch docs \
    -nW --keep-going \
    -b html \
    docs/ docs/_build/html
"""

[tasks.docnb]
cmd = """
sphinx-build \
    -nW --keep-going \
    -b html \
    docs/ docs/_build/html
"""
env = {EXECUTE_NB = "yes"}

[tasks.docnblive]
cmd = """
sphinx-autobuild \
    --watch docs \
    -nW --keep-going \
    -b html \
    docs/ docs/_build/html
"""
env = {EXECUTE_NB = "yes"}

[dependencies]
ampform = ">=0.15.4,<0.16"
black = ">=24.4.2,<24.5"
graphviz = ">=9.0.0,<9.1"
ipywidgets = ">=8.1.2,<8.2"
isort = ">=5.13.2,<5.14"
jax = ">=0.4.27,<0.5"
jaxlib = ">=0.4.23,<0.5"
jupyter = ">=1.0.0,<1.1"
jupyterlab = ">=4.2.0,<4.3"
jupyterlab-git = ">=0.50.0,<0.51"
jupyterlab-lsp = ">=5.1.0,<5.2"
jupyterlab-myst = ">=2.4.2,<2.5"
jupyterlab_code_formatter = ">=2.2.1,<2.3"
matplotlib = ">=3.8.4,<3.9"
myst-nb = ">=1.1.0,<1.2"
numpy = ">=1.26.4,<1.27"
phasespace = ">=1.10.3,<1.11"
pre-commit = ">=3.7.1,<3.8"
pydata-sphinx-theme = ">=0.15.2,<0.16"
python = ">=3.12.3,<3.13"
python-graphviz = ">=0.20.3,<0.21"
python-lsp-server = ">=1.11.0,<1.12"
qrules = ">=0.10.1,<0.11"
scipy = ">=1.13.0,<1.14"
sphinx-autobuild = ">=2024.4.16,<2024.5"
sphinx-book-theme = ">=1.1.2,<1.2"
sphinx-comments = ">=0.0.3,<0.1"
sphinx-copybutton = ">=0.5.2,<0.6"
sympy = ">=1.12,<2"
tensorflow = ">=2.16.1,<2.17"
tensorwaves = ">=0.4.12,<0.5"
