[project]
name = "gluex-nstar"
version = "0.1.0"
description = "Add a short description here"
authors = ["Vitor Shen <17490173+shenvitor@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
docnb = """
sphinx-build \
    -nW --keep-going \
    -b html \
    docs _build/html
"""
docnblive = """
sphinx-autobuild \
    --watch docs \
    -nW --keep-going \
    -b html \
    docs _build/html
"""

[dependencies]
jaxlib = ">=0.4.23,<0.5"
sympy = ">=1.12,<2"
python = ">=3.12.3,<3.13"
jupyterlab = ">=4.2.0,<4.3"
jax = ">=0.4.26,<0.5"
numpy = ">=1.26.4,<1.27"
black = ">=24.4.2,<24.5"
isort = ">=5.13.2,<5.14"
jupyterlab-git = ">=0.50.0,<0.51"
myst-nb = ">=1.1.0,<1.2"
python-graphviz = ">=0.20.3,<0.21"
sphinx-autobuild = ">=2024.4.16,<2024.5"
jupyterlab-lsp = ">=5.1.0,<5.2"
pre-commit = ">=3.7.1,<3.8"
jupyterlab-myst = ">=2.4.2,<2.5"
nodejs = ">=20.12.2,<20.13"
scipy = ">=1.13.0,<1.14"
