[project]
name = "gluex-nstar"
version = "0.1.0"
description = "Add a short description here"
authors = ["Vitor Shen <17490173+shenvitor@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
jaxlib = ">=0.4.23,<0.5"
sympy = ">=1.12,<2"
python = ">=3.12.3,<3.13"
jupyterlab = ">=4.2.0,<4.3"
jax = ">=0.4.26,<0.5"
numpy = ">=1.26.4,<1.27"
black = ">=24.4.2,<24.5"
isort = ">=5.13.2,<5.14"
jupyterlab-git = ">=0.50.0,<0.51"
