[project]
authors = ["Vitor Shen <17490173+shenvitor@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "gluex-nstar"
platforms = ["linux-64"]

[tasks]
docnb = """
sphinx-build \
    -nW --keep-going \
    -b html \
    docs/ docs/_build/html
"""
docnblive = """
sphinx-autobuild \
    --watch docs \
    -nW --keep-going \
    -b html \
    docs/ docs/_build/html
"""

[dependencies]
black = ">=24.4.2,<24.5"
isort = ">=5.13.2,<5.14"
jax = ">=0.4.26,<0.5"
jaxlib = ">=0.4.23,<0.5"
jupyterlab = ">=4.2.0,<4.3"
jupyterlab-git = ">=0.50.0,<0.51"
jupyterlab-lsp = ">=5.1.0,<5.2"
jupyterlab-myst = ">=2.4.2,<2.5"
myst-nb = ">=1.1.0,<1.2"
myst-parser = ">=3.0.1,<3.1"
nbsphinx = ">=0.9.4,<0.10"
numpy = ">=1.26.4,<1.27"
pre-commit = ">=3.7.1,<3.8"
pydata-sphinx-theme = ">=0.15.2,<0.16"
python = ">=3.12.3,<3.13"
python-graphviz = ">=0.20.3,<0.21"
scipy = ">=1.13.0,<1.14"
sphinx-autobuild = ">=2024.4.16,<2024.5"
sphinx_rtd_theme = ">=2.0.0,<2.1"
sympy = ">=1.12,<2"
