[project]
authors = ["Vitor Shen <17490173+shenvitor@users.noreply.github.com>"]
channels = ["conda-forge"]
license = "MIT"
license-file = "LICENSE"
name = "gluex-nstar"
platforms = ["linux-64"]
readme = "README.md"

[dependencies]
graphviz = "*"
python = "*"

[pypi-dependencies]
ampform = "*"
graphviz = "*"
ipywidgets = "*"
jax = "*"
jaxlib = "*"
jupyterlab = "*"
jupyterlab-code-formatter = "*"
jupyterlab-git = "*"
jupyterlab-lsp = "*"
jupyterlab-myst = "*"
matplotlib = "*"
myst-nb = "*"
numpy = "*"
pandas = "*"
phasespace = "*"
pre-commit = "*"
python-lsp-ruff = "*"
python-lsp-server = "*"
qrules = "*"
ruff = "*"
sphinx-autobuild = "*"
sphinx-book-theme = "*"
sphinx-comments = "*"
sphinx-copybutton = "*"
sympy = "*"
tensorflow = "*"
tensorwaves = "*"

[tasks.doc]
cmd = """
sphinx-build \
    -nW --keep-going \
    -b html \
    docs/ docs/_build/html
"""

[tasks.doclive]
cmd = """
sphinx-autobuild \
    --re-ignore '.*/_build/.*' \
    --re-ignore '.*/.ipynb_checkpoints/.*' \
    --re-ignore '.*/.virtual_documents/.*' \
    --watch docs \
    -nW --keep-going \
    -b html \
    docs/ docs/_build/html
"""

[tasks.docnb]
cmd = """
sphinx-build \
    -nW --keep-going \
    -b html \
    docs/ docs/_build/html
"""
env = {EXECUTE_NB = "yes"}

[tasks.docnblive]
cmd = """
sphinx-autobuild \
    --re-ignore '.*/_build/.*' \
    --re-ignore '.*/.ipynb_checkpoints/.*' \
    --re-ignore '.*/.virtual_documents/.*' \
    --watch docs \
    -nW --keep-going \
    -b html \
    docs/ docs/_build/html
"""
env = {EXECUTE_NB = "yes"}

[tasks.lab]
cmd = "jupyter lab docs"
