[project]
name = "gluex-nstar"
version = "0.1.0"
readme = "README.md"
requires-python = "~=3.13.0"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Vitor Shen" },
    { name = "Remco de Boer" },
]

[dependency-groups]
dev = [
    "ruff",
    { include-group = "doc" },
    { include-group = "jupyter" },
    { include-group = "test" },
]
doc = [
    "myst-nb",
    "sphinx-book-theme",
    "sphinx-comments",
    "sphinx-copybutton",
    { include-group = "notebooks" },
]
jupyter = [
    "jupyter-ruff",
    "jupyterlab",
    "jupyterlab-git",
    "jupyterlab-lsp",
    "jupyterlab-myst",
    "jupyterlab-quickopen",
    "python-lsp-ruff",
    "python-lsp-server",
    { include-group = "notebooks" },
]
notebooks = [
    "ampform",
    "ampform-dpd~=0.2.0",
    "ipympl",
    "ipywidgets",
    "matplotlib",
    "qrules[viz]",
    "tensorwaves[jax,pwa]",
]
test = [{ include-group = "notebooks" }]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.compwa.policy]
doc-apt-packages = "graphviz"
repo-name = "Symbolic Amplitudes for Light Baryons"

[tool.compwa.policy.github]
github-pages = true
no-cd = true
no-pypi = true

[tool.poe.executor]
isolated = true
no-group = "dev"
type = "uv"

[tool.poe.tasks.all]
help = "Run all continuous integration (CI) tasks locally"
sequence = [
    "style",
    "linkcheck",
    "docnb-force",
]

[tool.poe.tasks.style]
cmd = "pre-commit run --all-files"
help = "Perform all linting, formatting, and spelling checks"

[tool.poe.tasks.upgrade]
executor = { type = "simple" }
help = "Upgrade lock files"
parallel = ["_upgrade-precommit", "_upgrade-uv"]

[tool.poe.tasks._upgrade-precommit]
cmd = "pre-commit autoupdate -j8"
executor = { type = "simple" }

[tool.poe.tasks._upgrade-uv]
executor = { type = "simple" }
cmd = "uv lock --upgrade"

[tool.poe.groups.doc]
heading = "Documentation"

[tool.poe.groups.doc.tasks.doc]
cmd = """
sphinx-build \
    --builder=html \
    --fail-on-warning \
    --keep-going \
    --show-traceback \
    docs/ \
    docs/_build/html/
"""
env = { PYTHONWARNINGS = "" }
executor = { group = "doc" }
help = "Build documentation and API"

[tool.poe.groups.doc.tasks.doclive]
cmd = """
sphinx-autobuild \
    --builder=html \
    --port=0 \
    --re-ignore=/__pycache__(/.*)?$ \
    --re-ignore=/_build(/.*)?$ \
    --re-ignore=/\\.cache(/.*)?$ \
    --re-ignore=/\\.egg-info(/.*)?$ \
    --re-ignore=/\\.ipynb_checkpoints(/.*)?$ \
    --re-ignore=/\\.virtual_documents(/.*)?$ \
    --re-ignore=/api(/.*)?$ \
    --re-ignore=/docs$ \
    --re-ignore=/version\\.py$ \
    --re-ignore=\\.egg-info(/.*)?$ \
    --re-ignore=\\.png$ \
    --re-ignore=\\.svg$ \
    docs/ \
    docs/_build/html/
"""
executor = { group = "doc", with = "sphinx-autobuild" }
help = "Set up a server to directly preview changes to the HTML pages"

[tool.poe.groups.doc.tasks.docnb]
env = { EXECUTE_NB = "yes" }
help = "Build documentation and API with cached notebook execution"
sequence = ["doc"]

[tool.poe.groups.doc.tasks.docnb-force]
env = { FORCE_EXECUTE_NB = "yes" }
help = "Build documentation and API with notebook execution (no cache)"
sequence = ["doc"]

[tool.poe.groups.doc.tasks.docnblive]
env = { EXECUTE_NB = "yes" }
help = "Set up a server to directly preview changes to the HTML pages with cached notebook execution"
sequence = ["doclive"]

[tool.poe.groups.doc.tasks.linkcheck]
cmd = """
sphinx-build \
    --builder=linkcheck \
    --show-traceback \
    docs/ \
    docs/_build/linkcheck/
"""
env = { PYTHONWARNINGS = "" }
executor = { group = "doc" }
help = "Check external links in the documentation (requires internet connection)"

[tool.poe.groups.notebook]
heading = "Notebooks"

[tool.poe.groups.notebook.tasks.lab]
args = [{ name = "paths", default = "", positional = true }]
cmd = "jupyter lab ${paths}"
executor = { group = "jupyter" }
help = "Launch Jupyter Lab"

[tool.poe.groups.notebook.tasks.nb]
args = [{ name = "paths", default = "docs", multiple = true, positional = true }]
cmd = "pytest --nbmake --nbmake-timeout=0 ${paths}"
executor = { group = "notebooks", with = "nbmake" }
help = "Run all notebooks"

[tool.ruff]
extend-include = ["*.ipynb"]
preview = true
show-fixes = true

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"

[tool.ruff.lint]
ignore = [
    "DOC",
    "PTH",
    "any-type",
    "if-else-block-instead-of-if-exp",
    "incorrect-blank-line-before-class",
    "line-too-long",
    "logging-f-string",
    "missing-copyright-notice",
    "missing-dashed-underline-after-section",
    "missing-section-name-colon",
    "missing-trailing-comma",
    "multi-line-summary-second-line",
    "non-empty-init-module",
    "pytest-fixture-incorrect-parentheses-style",
    "read-whole-file",
    "reimplemented-starmap",
    "single-line-implicit-string-concatenation",
    "undocumented-magic-method",
    "undocumented-public-class",
    "undocumented-public-function",
    "undocumented-public-init",
    "undocumented-public-method",
    "unspecified-encoding",
    "write-whole-file",
]
preview = true
select = ["ALL"]
task-tags = ["cspell"]

[tool.ruff.lint.flake8-builtins]
ignorelist = ["display"]

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = [
    "ANN",
    "C90",
    "D",
    "PLR09",
    "T20",
    "TC00",
    "ambiguous-unicode-character-string",
    "assert",
    "global-statement",
    "global-variable-not-assigned",
    "import-private-name",
    "magic-value-comparison",
    "mixed-case-variable-in-global-scope",
    "non-ascii-name",
    "non-lowercase-variable-in-function",
    "too-many-blank-lines",
    "unnecessary-collection-call",
    "useless-expression",
    "useless-semicolon",
]
"docs/*" = [
    "assert",
    "implicit-namespace-package",
    "request-without-timeout",
]
"docs/conf.py" = [
    "builtin-variable-shadowing",
    "implicit-namespace-package",
    "undocumented-public-module",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.tombi.files]
exclude = ["**/uv.lock"]

[tool.tombi.format.rules]
indent-width = 4
line-width = 88

[tool.tombi.lint.rules]
key-empty = "off"

[[tool.tombi.schemas]]
root = "tool.compwa.policy"
path = "https://raw.githubusercontent.com/ComPWA/policy/0.9.3/compwa-policy.schema.json"
include = ["pyproject.toml"]
