name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: |-
    ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}

env:
  PYTHONHASHSEED: "0"

on:
  push:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:
    inputs:
      specific-pip-packages:
        description: Run CI with specific pip packages
        required: false
        type: string

jobs:
  doc:
    uses: ComPWA/actions/.github/workflows/ci-docs.yml@v2
    permissions:
      pages: write
      id-token: write
    with:
      gh-pages: true
      specific-pip-packages: ${{ inputs.specific-pip-packages }}
