name: PR linting
jobs:
  lint-pr:
    uses: ComPWA/actions/.github/workflows/pr-linting.yml@v1
on:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled
